{
	"name": "ContextSensitive",
	"version": "1.0.10",
	"author": "ProjectAlice",
	"maintainers": [
		"Psycho",
		"maxbachmann"
	],
	"desc": "ContextSensitive is the official context sensitive module. It handle intents like 'Delete this', 'Forget about that'",
	"aliceMinVersion": "1.0.0-a4",
	"systemRequirements": [],
	"pipRequirements": [],
	"conditions": {
		"lang": [
			"en",
			"fr",
			"de"
		]
	}
}
