{
	"name": "FindMyPhone",
	"version": 0.4,
	"author": "Psychokiller1888",
	"maintainers": ["maxbachmann"],
	"desc": "Using ifttt one can ask Alice to find his phone. sets the ring tone at max volume and initiates a call on it.",
	"aliceMinVersion": "",
	"systemRequirements": [],
	"pipRequirements": [],
	"conditions": {
		"lang": [
			"en",
			"fr",
			"de"
		],
		"module": [
			{
				"name": "Ifttt",
				"url": "http://modules.projectalice.ch/ifttt"
			}
		],
		"online": true
	}
}
